baseURL: "https://example.com"
languageCode: "en-us"
title: "Carina Mirzaeva"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  instagram: "https://www.instagram.com/carrylionart/"
  linkedin: "https://www.linkedin.com/in/carrylion/"
  vimeo: "https://vimeo.com/carrylion"
  tumblr: "https://carrylion.tumblr.com/"
taxonomies:
  author: authors
